sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.10
- 2.3.8
- 2.4.7
- 2.5.6
- 2.6.4
script:
- bundle exec rake
gemfile:
- gemfiles/faraday_0.9.gemfile
- gemfiles/faraday_0.10.gemfile
- gemfiles/faraday_0.11.gemfile
- gemfiles/faraday_0.12.gemfile
- gemfiles/faraday_0.13.gemfile
- gemfiles/faraday_0.14.gemfile
